Create courses functionality for creating, listing, and joining courses
nu25/hoosky-bot pull request #16
Opened 2021-06-19 07:57 UTC by SamHaggans

This creates six new commands with the bot:

1.     /course create [name] [crn] [description] - Creates a new course and associated role in discord. Requires the Manage Roles permission.
2.     /course remove [role] - Removes a given course and the associated role. Requires the Manage Roles permission.
3.     /course join [role] - Joins a course and assigns the appropriate course role to the user.
4.     /course leave [role] - Leaves a class and removes the appropriate course role from the user.
5.     /course list - Lists the available courses that can be joined in a message only visible to the requested user.
6.     /course roster [role] - Lists the members currently in that course.

2021-06-19 14:07 UTC, j-651 requested changes
This looks great! I left one requested change to switch the `displayName` for `remove`. I also committed documentation for `COMMANDS.md`.

2021-06-19 14:07 UTC, j-651 commented on src/commands/course/subcommands/_roster.ts
> +  displayName: 'Returns a roster of members in a course',
```suggestion
  displayName: 'Course Roster',
```

2021-06-19 17:25 UTC, thederekkaplan requested changes
As discussed in the Discord:
- [ ] Change from using CRNs to course numbers
- [ ] Use `_id` to store in database

2021-06-19 17:52 UTC, thederekkaplan approved these changes

2021-06-19 18:02 UTC, aiyan requested changes
Are we going to change the number system to the subject code + 4-digit number?

2021-06-19 19:03 UTC, j-651 approved these changes

2021-06-20 01:35 UTC, aiyan approved these changes

2021-06-20 01:40 UTC, thederekkaplan requested changes

2021-06-20 01:40 UTC, thederekkaplan commented on src/commands/course/_common.ts
> +  _id: number;
If we're using just the number and not also the course prefix as _id, then it'll create a conflict between courses in different subjects with the same number.

2021-06-20 13:52 UTC, j-651 requested changes

2021-06-20 13:52 UTC, j-651 commented on src/ExecutionContext.ts
> +  }
These are missing documentation `/** */`

2021-06-20 13:52 UTC, j-651 commented on src/commands/course/_common.ts
> +    .deleteOne({ roleId: courseInfo.roleId });
Can `coursesCollection()` be used here instead?
```suggestion
  coursesCollection(ctx, guildId).deleteOne({ roleId: courseInfo.roleId }));
```

2021-06-20 13:52 UTC, j-651 commented on src/commands/course/subcommands/_list.ts
> +    );
To match what was done with `resondSilently()` should a `respondWithSilentEmbed()` be created?

2021-06-20 13:52 UTC, j-651 commented on src/commands/course/subcommands/_roster.ts
> +    );
`respondWithSilentEmbed()`

2021-06-20 14:24 UTC, thederekkaplan approved these changes

2021-06-20 14:25 UTC, j-651 approved these changes

2021-06-20 14:26 UTC, merged